/* ════════════════════════════════════════════════════
   appInfo.js — métadonnées app + changelog (BRIEF_A_PROPOS)
   ────────────────────────────────────────────────────
   Version visible dans la modale "À propos" (Paramètres → bas).
   À mettre à jour à chaque release notable.

   Convention :
     - Garder 5-6 entrées max dans CHANGELOG (les + récentes).
     - L'entrée d'index 0 reçoit le badge NOUVEAU dans l'UI.
     - Pas de rouge / vert dans les emojis (palette café-only).
═══════════════════════════════════════════════════════ */

export const APP_INFO = {
  version: '1.16.0',
  releaseDate: '2026-05-12',
  github: 'https://github.com/Cookithan/cookitrader',
  description: "App mobile de récompenses café & cookies. Mini-jeux quotidiens, marché spéculatif $CKM, classement, amis et boutique premium.",
  author: 'Ethan Cuomo',
};

export const CHANGELOG = [
  {
    version: '1.16.0',
    date: '2026-05-12',
    title: '⚡ Perf + UX polish + Ordre Bulk $CKM',
    changes: [
      "⚡ App 2× plus rapide à charger (bundle initial divisé par 2)",
      "🎬 Transition entre onglets totalement refondue (glisse iOS-like)",
      "📳 Vibrations subtiles sur les actions clés (achat, niveau, succès)",
      "💫 Animations skeleton dorées sur le classement pendant le chargement",
      "🛡️ Plus d'écran blanc en cas de bug — écran de récupération propre",
      "🔄 Maintenance & mises à jour pilotables en live (sans deploy)",
      "📈 Cap actions $CKM par transaction : 20 → 30",
      "📦 Nouvel item premium : Ordre Bulk $CKM (3 ☕) — achète OU vends d'un coup tout ton portefeuille (bypass cap, cumulable)",
      "⬆️ XP niveaux 9-12 adouci (-25%) — fin du mur post-niveau 8",
    ],
  },
  {
    version: '1.15.0',
    date: '2026-05-11',
    title: '🎮 Flappy Cookie + niveaux 16-25 + Discord communauté',
    changes: [
      "🎮 Nouveau mini-jeu Flappy Cookie (niv 12) — 3 modes Facile/Normal/Difficile, esquive les tuyaux espresso",
      "✨ Tuyaux clairs aléatoires (×2 reward) et bonus rares à dénicher",
      "⬆️ Extension à 25 niveaux : Ascendant Caféiné → Origine du Cookie (le palier final endgame est désormais au niv 25)",
      "🛍️ 13 nouveaux items boutique pour les niveaux 16-25 (badges, titres, skins, thèmes)",
      "🌋 Thème Forge Caféinée — palette volcanique sombre + or saturé",
      "⚡ 3 boosts premium en plus : Boost +30 % (24 h), Recharges Gratuites (24 h), Streak Save",
      "💬 Serveur Discord intégré (accueil + paramètres + à propos) pour bugs & suggestions",
      "🥞 Pile de Tasses : cap quotidien 50 → 100 + recharge 2 ☕ → 1 ☕",
      "🎰 Roue & Machine à Sous : recharge 2 ☕ → 1 ☕",
      "🧠 Memory Café : aperçu 0,5 s de toutes les cartes au démarrage",
      "🍪 Cookie Click : refonte douce (auto-fin au cap, +1 🍪 par clic, plus équilibré)",
      "📊 Rééquilibrage XP : progression du niv 3 au niv 24 plus posée pour valoriser la montée",
      "🛡️ Système de patches Supabase cross-device — fini les doubles pop-ups au changement d'appareil",
      "🎯 Modale 'Voir détails' du classement enfin centrée à l'écran",
      "☕ Stop le café : fini les arrêts inopinés quand le doigt glisse hors du bouton",
    ],
  },
  {
    version: '1.14.0',
    date: '2026-05-11',
    title: '🎮 Pile de Tasses & Cookie Click — diversifiés + recharge in-game',
    changes: [
      "🥞 Pile de Tasses : 3 modes au choix (Normal / Rapide / Précision) avec caps adaptés",
      "✨ Pile de Tasses : tasses spéciales aléatoires (dorée bonus, fragile, large) dès 5 tasses posées",
      "🍪 Cookie Click : 3 modes (Normal 5 s / Rapide 3 s / Frénétique 8 s avec cookie qui bouge)",
      "🔥 Cookie Click : les combos x2/x3/x4 boostent vraiment le reward (avant : juste visuels)",
      "🎰 Roue & Machine à Sous : recharge directe pour 2 ☕ quand le quota est atteint",
      "🛒 Plus besoin d'aller dans la boutique premium pour racheter des tours / parties",
      "⏳ Pile de Tasses : 50 essais quotidiens, recharge 2 ☕ pour repartir à 50",
    ],
  },
  {
    version: '1.13.0',
    date: '2026-05-10',
    title: '🌐 Présence en ligne + nouveau thème + +32 questions de quiz',
    changes: [
      "🟡 Indicateur « X joueurs en ligne » dans le classement, le profil ami et À propos (heartbeat 60 s)",
      "🏆 Classement Cookies revient sur le total lifetime (le cycle hebdomadaire continue en interne pour les récompenses top 3)",
      "☕ Nouveau thème édition limitée « Cookie & Espresso » — gradient vertical crème → espresso, drop barista légendaire",
      "📲 Carte d'installation PWA directement dans l'onboarding (Android/Desktop) + instruction Safari pour iOS",
      "🧠 Pool de quiz enrichi : 65 questions au lieu de 33 (+22 culture café + 10 nouvelles Expert : pression espresso 9 bars, Geisha Panama, Yirgacheffe…)",
      "🎟️ De nouveaux codes promo à dénicher (cookies, café, action $CKM)",
      "🛡️ Fix anti-exploit : les packs actions $CKM en cookies deviennent achetables une seule fois (avant : achat répété possible)",
      "📛 Pseudo « Ethan Cuomo » dans les crédits, le splash et les mentions de l'auteur",
      "✨ Petit polish UI : nom long du leader plus jamais coupé dans le classement, titre lisible sur le nouveau thème",
    ],
  },
  {
    version: '1.12.0',
    date: '2026-05-10',
    title: '📈 Refonte du marché $CKM — anti-manipulation',
    changes: [
      "📊 Marché élargi : 10 000 actions disponibles (au lieu de 1 000)",
      "💎 Bonus de hold : +10 % après 1 h, +30 % après 24 h, +100 % après 7 jours sur la PnL positive — récompense les hodlers patients",
      "⏱️ Cooldown 60 s entre 2 achats / 2 ventes / achat puis vente — fini le pump-and-dump rapide",
      "🛒 Max 20 actions par transaction (force à étaler ses gros ordres)",
      "🛡️ Circuit breaker auto si variation > 15 % en 5 min (pause 1 h)",
      "🔄 Mean reversion vers 100 — le prix revient naturellement vers son centre",
      "📉 Cap 5 % du marché par utilisateur (500 actions max — plus de whales)",
      "🏆 Bannières podium top 1-3 redesignées en mocha-caramel chaud",
      "⚖️ Cap écart top 1 / top 2 : +25 % (compétition plus serrée)",
      "🤝 Compensation automatique pour les ex-investisseurs lésés par l'incident pump-and-dump",
    ],
  },
  {
    version: '1.11.0',
    date: '2026-05-10',
    title: '⚖️ Rééquilibrage économique — fair-play renforcé',
    changes: [
      "🛡️ Suppression des items qui donnaient un avantage compétitif (Coup de Grâce, packs cookies, packs gros volumes d'actions)",
      "⚡ Boost café réajusté : +30 % au lieu de ×2 (impact plus modéré sur la progression)",
      "💎 La boutique premium garde uniquement avatars / skins / thèmes / musiques / 1 action $CKM (cosmétiques + utilitaires fair)",
      "🎯 Doubler le prochain gain et Skip Quiz toujours dispo — utilitaires limités",
      "🎫 Jetons VIP roue & slot inchangés — juste +tours, pas d'avantage",
      "🏆 Le marché et le classement deviennent purement compétitifs, sans raccourci payant",
    ],
  },
  {
    version: '1.10.0',
    date: '2026-05-10',
    title: '🎨 Cosmétiques premium + raretés ☕',
    changes: [
      "🧑‍🚀 Avatar Cosmonaute Caféiné (25 ☕) + Skin Cookie Galactique (7 ☕)",
      "⏰ Bonus VIP cappés à 1 achat / jour — fini le cumul de boosts",
      "⚡ Popup festif quand un boost amplifie un gain mini-jeu",
      "💳 Bundle Stripe 0,99 € : 10 ☕ → 15 ☕ (meilleur ratio entry-level)",
      "🌑 Fix : nav du bas ne disparaît plus en thème Noir & Blanc",
      "🍪 Décor festif : cookies tournants en arrière-plan pour le thème Pâte de Cookie",
    ],
  },
  {
    version: '1.9.0',
    date: '2026-05-10',
    title: '☕ Monétisation, prestige & refonte café',
    changes: [
      "💳 Paiement Stripe pour acheter des cafés (15 / 50 / 200 ☕)",
      "🌟 Système Prestige (Renaissance) — niveau 16 'Ascendant Caféiné' à 20000 XP",
      "👑 Couronnes visibles dans le classement à chaque prestige (×10 % bonus permanent sur tous les gains 🍪)",
      "⚡ Nouveaux boosters consommables : ×2 cookies (1 h), Skip quiz, Doubler prochain gain",
      "🎫 Catégorie 'Bonus VIP' regroupe tous les jetons + boosters dans le Premium",
      "🎰 Cap 50 parties / jour sur la Machine à Sous + ticket 50 parties (3 ☕)",
      "🐺 Avatar Loup Mocha (remplace Dragon Espresso) — fourrure mocha sur fond espresso sombre",
      "🌑 Thème exclusif 'Noir & Blanc' (greyscale total) — code promo distribué par le créateur",
      "🍪 Thème 'Pâte de Cookie' — drop ultra-rare à dénicher en jeu",
      "🎓 Tutoriel élargi : 7 étapes couvrant classement, marché, boutique en plus",
      "💰 Économie café rééquilibrée : sources -45 %, stock global reset à 0",
      "🐛 Fix : sync cross-device cassait les paiements Stripe (race upsert client)",
    ],
  },
  {
    version: '1.8.0',
    date: '2026-05-09',
    title: '🛍️ Boutique enrichie + audio complet',
    changes: [
      "🎨 9 nouveaux skins cookie (Caramel, Onyx, Doré, Phoenix, Originel…)",
      "🏷️ 9 titres couleur shimmer pour ton pseudo (Mousse → Cosmique)",
      "🎵 5 nouvelles musiques (Café du Matin, Velvet Smoke, Beat de l'Empereur, Veillée Lofi, Nuit Cosmique)",
      "📈 Packs $CKM — achète directement 5 ou 10 actions",
      "🎟️ Item premium 'Révéler Code Promo Rare' (5 ☕ niv 13)",
      "🔊 8 sons d'effets dédiés (caisse, jackpot, slot, bulle…)",
      "💧 Bruit du café qui coule pendant le 'Stop le café'",
      "🪟 Sons sur tous les jeux silencieux (Click, Memory, Reflex, Devine)",
      "👤 Sélecteurs Skin & Titre dans le profil",
      "🛒 Chaque niveau a maintenant 3 ou 4 items à débloquer",
    ],
  },
  {
    version: '1.7.0',
    date: '2026-05-09',
    title: '🎰 Niveaux 11-15 + Machine à Sous',
    changes: [
      "🆙 5 nouveaux niveaux : Empereur Caféiné → Cookie Originel",
      "🎰 Nouveau mini-jeu Machine à Sous (débloqué niv 13)",
      "🛡️ 3 badges et 2 thèmes en plus dans la boutique",
      "🌌 Endgame XP→☕ décalé du niv 10 au niv 15 — plus de progression",
      "📜 Restauration complète de profil avec PIN sécurisé",
      "🔄 Récupère ton compte sur un autre appareil avec ton code + PIN",
    ],
  },
  {
    version: '1.6.0',
    date: '2026-05-08',
    title: '🎁 Cadeaux + niveaux 7-9 + anti-triche',
    changes: [
      "🎁 Offrir 50 🍪 ou 1 ☕ à un ami (max 3 cadeaux par jour)",
      "🏗️ Nouveau mini-jeu Pile de Tasses (niv 8) — empile sans tomber",
      "⬆️ Niveaux 7-9 remplis : Mocha Cosmique, Sage du Café, Maître Mythique",
      "💫 Bonus passif +15 % XP à partir du niveau 9",
      "🎓 Mode Expert Devine la commande (niv 7+, V60 / Geisha / Chemex…)",
      "🎰 Roue à 20 🍪 dès le niveau 8",
      "🛡️ Anti-triche Cookie Clicker v2 (cap 12 clics/s, détection pattern)",
      "🔇 Musique en pause quand l'app passe en arrière-plan",
      "🎨 Avatars : 8 onboarding + 9 premium thématisés café/cookie",
      "🐛 Fix : amitiés bloquées en pending par une RLS manquante",
    ],
  },
  {
    version: '1.5.0',
    date: '2026-05-07',
    title: '📈 Marché en ligne + réseau social',
    changes: [
      "📈 Marché $CKM 100 % online avec offre/demande partagée entre joueurs",
      "🏆 Classement marché par actions $CKM détenues",
      "⏰ Horaires marché : 6 h → minuit (heure locale)",
      "👥 Demandes d'amis bilatérales (envoyer / accepter / refuser)",
      "👤 Voir le profil d'un ami ou du top 1 du classement",
      "💬 Réactions emoji depuis le profil (👏 ☕ 🔥 🍪)",
      "📬 Inbox de notifications centralisée",
      "🏅 3 nouveaux badges secrets à découvrir",
      "🎉 Événements spéciaux : 3 défis avec thèmes limités + bonus ☕",
      "🐛 Fix : reset complet du profil + avatars cross-device",
    ],
  },
  {
    version: '1.4.0',
    date: '2026-05-06',
    title: '🎵 Audio complet',
    changes: [
      "🔊 Sons d'interface partout (tap, succès, modale…)",
      "🎵 4 musiques d'ambiance (Jazz Café, Bossa Nova, Café Parisien, Lounge Doré)",
      "☕ Pack premium ☕ : Lofi + Symphonie Royale",
      "🔇 Mute global + sélection de la piste en cours",
    ],
  },
  {
    version: '1.3.0',
    date: '2026-05-05',
    title: '☁️ Backend Supabase',
    changes: [
      "🌍 Profil synchronisé en ligne via Supabase",
      "🏆 Classement online avec vrais joueurs",
      "🎓 Tutoriel guidé pour les nouveaux",
      "✨ Splash screen lettre par lettre",
      "📱 PWA installable sur l'écran d'accueil",
    ],
  },
];
