/* ════════════════════════════════════════════════════
   changelogArchive.js — l'histoire complète de l'app (v1.0 → v1.22)
   ────────────────────────────────────────────────────
   CHANGELOG (appInfo.js) ne garde que les 5-6 dernières versions,
   pour que la modale À propos reste lisible. Les entrées plus anciennes
   étaient donc simplement SUPPRIMÉES à chaque release : toute l'histoire
   de l'app avait disparu de l'app elle-même.

   Ce fichier la rétablit. Les 25 entrées ci-dessous ont été RECONSTRUITES
   depuis l'historique git de appInfo.js (chaque commit relu, entrées
   dédupliquées par version) — rien n'a été réécrit ni inventé.

   Affichage : AboutModal, derrière « Voir toutes les versions ».

   ⚠️ À la prochaine release, l'entrée qui sort de CHANGELOG doit être
   COLLÉE EN TÊTE d'ici — sinon elle est perdue une seconde fois.
═══════════════════════════════════════════════════════ */

export const CHANGELOG_ARCHIVE = [
  {
    version: '1.22.0',
    date: '2026-05-18',
    title: "🏦 Boutique Actions + roue ajustée",
    title_en: "🏦 Shares Shop + tuned wheel",
    changes: [
      "🏦 Nouvelle Boutique Actions : accumule des actions $CKM et débloque-la pour échanger tes actions contre des récompenses exclusives (thèmes, avatars, cafés…)",
      "📈 Un repère dans le Marché t'indique ta progression vers son déblocage",
      "🎡 Roue : les petits gains du palier intermédiaire ont été revalorisés",
      "🛒 Correctif : un pack d'actions $CKM acheté ne reste plus affiché à tort dans la boutique",
    ],
    changes_en: [
      "🏦 New Shares Shop: stack up $CKM shares and unlock it to trade your shares for exclusive rewards (themes, avatars, coffees…)",
      "📈 A marker in the Market shows your progress toward unlocking it",
      "🎡 Wheel: the mid-tier small wins have been bumped up",
      "🛒 Fix: a purchased $CKM shares pack no longer wrongly stays shown in the shop",
    ],
  },
  {
    version: '1.21.0',
    date: '2026-05-17',
    title: "🏆 Classement hebdo remis à zéro + roue rééquilibrée",
    title_en: "🏆 Weekly leaderboard reset + rebalanced wheel",
    changes: [
      "🏆 Le classement repart à zéro : une nouvelle course chaque semaine, le podium est à prendre (tes cookies, ton niveau et tes récompenses restent 100 % intacts)",
      "🎡 La roue est rééquilibrée et adaptée à ton niveau — trois paliers de mises et de gains, plus de suspense",
      "🌍 Le mini-jeu « Devine la commande » est désormais entièrement traduit en anglais",
      "📊 Chaque ligne du classement affiche le score de la semaine ET le total cumulé du joueur",
    ],
    changes_en: [
      "🏆 The leaderboard is reset: a fresh race every week, the podium is yours to grab (your cookies, level and rewards stay 100% intact)",
      "🎡 The wheel is rebalanced and scaled to your level — three tiers of stakes and rewards, more suspense",
      "🌍 The \"Guess the order\" mini-game is now fully translated to English",
      "📊 Every leaderboard row shows the weekly score AND the player's all-time total",
    ],
  },
  {
    version: '1.20.1',
    date: '2026-05-14',
    title: "🎟️ Codes promo verrouillés cross-device",
    title_en: "🎟️ Promo codes locked cross-device",
    changes: [
      "🎟️ Les codes promo ne peuvent plus être réutilisés en changeant d'appareil — un code = une seule fois par compte, où que tu te connectes",
    ],
    changes_en: [
      "🎟️ Promo codes can no longer be reused by switching devices — one code = one redemption per account, anywhere you log in",
    ],
  },
  {
    version: '1.20.0',
    date: '2026-05-14',
    title: "🌍 App bilingue FR / EN + marché libéré",
    title_en: "🌍 Bilingual app FR / EN + market unleashed",
    changes: [
      "🌍 L'app est maintenant entièrement traduite en anglais — bascule la langue depuis les Paramètres",
      "📈 Le marché ne tire plus le prix vers 100 — la courbe peut s'envoler ou plonger plus longtemps",
      "🔔 Les pops d'amis acceptés ne réapparaissent plus quand tu te connectes sur un autre appareil",
    ],
    changes_en: [
      "🌍 The app is now fully translated to English — switch language from Settings",
      "📈 The market no longer pulls the price back toward 100 — the curve can fly higher or dive longer",
      "🔔 Accepted-friend pop-ups no longer reappear when you log in on another device",
    ],
  },
  {
    version: '1.19.3',
    date: '2026-05-14',
    title: "🎡 Roue plus généreuse + surprises cachées",
    title_en: "🎡 More generous Wheel + hidden surprises",
    changes: [
      "🎡 La roue est rééquilibrée 75/25 : trois fois plus de gains que de pertes (les pertes mordent encore mais beaucoup moins souvent)",
      "✨ De nouvelles surprises planquées dans certains mini-jeux — très rares à dénicher, gros bonus quand ça tombe",
    ],
    changes_en: [
      "🎡 The wheel is rebalanced 75/25: three times more wins than losses (losses still bite but much less often)",
      "✨ New surprises tucked away in some mini-games — very rare to find, big bonus when it drops",
    ],
  },
  {
    version: '1.19.2',
    date: '2026-05-14',
    title: "📲 Vraie installation PWA + 🎁 Coffres Mystères",
    title_en: "📲 Real PWA install + 🎁 Mystery Chests",
    changes: [
      "📲 L'app peut maintenant s'installer comme une vraie app — mode offline, mises à jour gérées proprement, plus un raccourci dans le navigateur",
      "🎁 Nouvelle section « Coffres Mystères » dans la boutique premium — chaque coffre se découvre en une seule ouverture et révèle 3 cosmétiques cachés",
      "🥉 3 tiers à débloquer selon ton niveau : Bronze, Or et Légendaire — la rareté monte avec le prix",
    ],
    changes_en: [
      "📲 The app can now install like a real native app — offline mode, properly handled updates, no longer just a browser shortcut",
      "🎁 New \"Mystery Chests\" section in the premium shop — each chest opens once and reveals 3 hidden cosmetics",
      "🥉 3 tiers to unlock by level: Bronze, Gold and Legendary — rarity climbs with price",
    ],
  },
  {
    version: '1.19.1',
    date: '2026-05-13',
    title: "🎉 Palier communautaire 500 000 🍪 + polish marché",
    title_en: "🎉 500,000 🍪 community milestone + market polish",
    changes: [
      "🎉 Palier communautaire : la communauté a miné 500 000 cookies — un cadeau pour tous les joueurs",
      "⚡ Renommage : « Ordre Bulk $CKM » devient « Trade Express $CKM » (plus clair pour les nouveaux)",
      "🎁 De nouveaux codes promo à dénicher sur les réseaux",
      "✨ De nouvelles surprises planquées dans la boutique…",
    ],
    changes_en: [
      "🎉 Community milestone: the community has mined 500,000 cookies — a gift for all players",
      "⚡ Rename: \"$CKM Bulk Order\" becomes \"$CKM Express Trade\" (clearer for newcomers)",
      "🎁 New promo codes to dig up on social media",
      "✨ New surprises tucked away in the shop…",
    ],
  },
  {
    version: '1.19.0',
    date: '2026-05-13',
    title: "📊 Marché vivant + popup système",
    title_en: "📊 Live market + system popup",
    changes: [
      "📰 Activité des autres joueurs visible sous la courbe (3 dernières transactions)",
      "📊 Pouls du marché : nb de traders 24 h, volume, ratio achats/ventes en un coup d'œil",
      "✨ Le prix flashe en temps réel à chaque variation (or hausse / moka baisse)",
      "👆 Glisse ton doigt sur la courbe : prix + heure exacte à chaque instant",
      "⏳ Carte Mes Actions enrichie : durée de hold + bonus actif + jauge prochain palier",
      "⚡ Cooldown entre 2 achats $CKM ramené à 15 s (vs 60 s) — réagis enfin en direct",
      "⚖️ Anti-monopole renforcé : top 1 du classement cookies plafonné automatiquement",
      "📣 Nouveau : popup d'annonces pilotées en live (maintenance, événements, mises à jour)",
      "❓ +30 questions au Quiz, +15 commandes au mini-jeu Devine la commande",
      "🔊 Son du bonus Flappy Cookie atténué",
    ],
    changes_en: [
      "📰 Other players' activity visible under the chart (last 3 transactions)",
      "📊 Market pulse: 24h traders count, volume, buy/sell ratio at a glance",
      "✨ The price flashes in real time at every change (gold up / mocha down)",
      "👆 Drag your finger on the chart: price + exact time at every point",
      "⏳ Enriched My Shares card: holding duration + active bonus + next tier gauge",
      "⚡ Cooldown between 2 $CKM buys reduced to 15s (vs 60s) — finally react in real time",
      "⚖️ Stronger anti-monopoly: top 1 of the cookies leaderboard is auto-capped",
      "📣 New: live-driven announcement popups (maintenance, events, updates)",
      "❓ +30 Quiz questions, +15 commands in the Guess the order mini-game",
      "🔊 Flappy Cookie bonus sound dimmed",
    ],
  },
  {
    version: '1.18.0',
    date: '2026-05-13',
    title: "⏱️ Temps total joué + progression XP adoucie",
    title_en: "⏱️ Total playtime + smoother XP progression",
    changes: [
      "⏱️ Nouveau : temps total passé sur l'app affiché dans ton profil et celui des autres joueurs",
      "⬆️ Niveaux 6 à 14 adoucis : fini le mur brutal au passage du 6 → 7 (progression ~×1.33 par palier)",
      "🐛 Fix d'affichage Android pour les utilisateurs avec un titre couleur animé",
    ],
    changes_en: [
      "⏱️ New: total time spent on the app shown in your profile and on other players' profiles",
      "⬆️ Levels 6-14 softened: no more brutal wall at 6 → 7 (progression ~×1.33 per tier)",
      "🐛 Android rendering fix for users with an animated color title",
    ],
  },
  {
    version: '1.17.0',
    date: '2026-05-13',
    title: "🎰 Refonte mini-jeux + UX fluide",
    title_en: "🎰 Mini-games overhaul + smooth UX",
    changes: [
      "🎡 Roue : 10 segments alternés gain/perte, 50/50 pile, événement spectaculaire sur jackpot +200",
      "🎰 Machine à Sous plus généreuse : gains boostés (jackpot 750→1000), probabilités x2 sur les triples, paire +25→+35",
      "🐦 Flappy Cookie : café bonus plus fréquent (% variable par mode), nouveau son de saut, ombre du cookie retirée",
      "☕ Stop le café : hitbox du bouton élargie (plus de lâché frustrant), tasse redessinée + recentrée sur l'assiette",
      "🍪 Cookie Click : 2 clics = 1 🍪 + retrait du cap, timer & barre parfaitement synchronisés",
      "🌟 Renaissance : la série de check-ins (streak) est désormais conservée",
      "🛡️ Anti-triche refondu : zéro faux positif pour les joueurs rapides",
      "🚀 App entièrement fluide : retour à un bundle unique, plus de chargements en cascade",
    ],
    changes_en: [
      "🎡 Wheel: 10 alternating win/loss segments, 50/50 split, spectacular event on +200 jackpot",
      "🎰 More generous Slot Machine: boosted wins (jackpot 750→1000), x2 triple odds, pair +25→+35",
      "🐦 Flappy Cookie: more frequent coffee bonus (% varies by mode), new jump sound, cookie shadow removed",
      "☕ Stop the coffee: enlarged button hitbox (no more frustrating drops), redesigned cup + recentered on the saucer",
      "🍪 Cookie Click: 2 clicks = 1 🍪 + cap removed, timer & bar perfectly synced",
      "🌟 Renaissance: the check-in streak is now preserved",
      "🛡️ Anti-cheat overhauled: zero false positives for fast players",
      "🚀 Fully smooth app: back to a single bundle, no more cascading loads",
    ],
  },
  {
    version: '1.16.0',
    date: '2026-05-12',
    title: "⚡ Perf + UX polish + Ordre Bulk $CKM",
    changes: [
      "⚡ App 2× plus rapide à charger (bundle initial divisé par 2)",
      "🎬 Transition entre onglets totalement refondue (glisse iOS-like)",
      "📳 Vibrations subtiles sur les actions clés (achat, niveau, succès)",
      "💫 Animations skeleton dorées sur le classement pendant le chargement",
      "🛡️ Plus d'écran blanc en cas de bug — écran de récupération propre",
      "🔄 Maintenance & mises à jour pilotables en live (sans deploy)",
      "📈 Cap actions $CKM par transaction : 20 → 30",
      "📦 Nouvel item premium : Ordre Bulk $CKM (3 ☕) — achète OU vends d'un coup tout ton portefeuille (bypass cap, cumulable)",
      "⬆️ XP niveaux 9-12 adouci (-25%) — fin du mur post-niveau 8",
    ],
  },
  {
    version: '1.15.0',
    date: '2026-05-11',
    title: "🎮 Flappy Cookie + niveaux 16-25 + Discord communauté",
    changes: [
      "🎮 Nouveau mini-jeu Flappy Cookie (niv 12) — 3 modes Facile/Normal/Difficile, esquive les tuyaux espresso",
      "✨ Tuyaux clairs aléatoires (×2 reward) et bonus rares à dénicher",
      "⬆️ Extension à 25 niveaux : Ascendant Caféiné → Origine du Cookie (le palier final endgame est désormais au niv 25)",
      "🛍️ 13 nouveaux items boutique pour les niveaux 16-25 (badges, titres, skins, thèmes)",
      "🌋 Thème Forge Caféinée — palette volcanique sombre + or saturé",
      "⚡ 3 boosts premium en plus : Boost +30 % (24 h), Recharges Gratuites (24 h), Streak Save",
      "💬 Serveur Discord intégré (accueil + paramètres + à propos) pour bugs & suggestions",
      "🥞 Pile de Tasses : cap quotidien 50 → 100 + recharge 2 ☕ → 1 ☕",
      "🎰 Roue & Machine à Sous : recharge 2 ☕ → 1 ☕",
      "🧠 Memory Café : aperçu 0,5 s de toutes les cartes au démarrage",
      "🍪 Cookie Click : refonte douce (auto-fin au cap, +1 🍪 par clic, plus équilibré)",
      "📊 Rééquilibrage XP : progression du niv 3 au niv 24 plus posée pour valoriser la montée",
      "🛡️ Système de patches Supabase cross-device — fini les doubles pop-ups au changement d'appareil",
      "🎯 Modale 'Voir détails' du classement enfin centrée à l'écran",
      "☕ Stop le café : fini les arrêts inopinés quand le doigt glisse hors du bouton",
    ],
  },
  {
    version: '1.14.0',
    date: '2026-05-11',
    title: "🎮 Pile de Tasses & Cookie Click — diversifiés + recharge in-game",
    changes: [
      "🥞 Pile de Tasses : 3 modes au choix (Normal / Rapide / Précision) avec caps adaptés",
      "✨ Pile de Tasses : tasses spéciales aléatoires (dorée bonus, fragile, large) dès 5 tasses posées",
      "🍪 Cookie Click : 3 modes (Normal 5 s / Rapide 3 s / Frénétique 8 s avec cookie qui bouge)",
      "🔥 Cookie Click : les combos x2/x3/x4 boostent vraiment le reward (avant : juste visuels)",
      "🎰 Roue & Machine à Sous : recharge directe pour 2 ☕ quand le quota est atteint",
      "🛒 Plus besoin d'aller dans la boutique premium pour racheter des tours / parties",
      "⏳ Pile de Tasses : 50 essais quotidiens, recharge 2 ☕ pour repartir à 50",
    ],
  },
  {
    version: '1.13.0',
    date: '2026-05-10',
    title: "🌐 Présence en ligne + nouveau thème + +32 questions de quiz",
    changes: [
      "🟡 Indicateur « X joueurs en ligne » dans le classement, le profil ami et À propos (heartbeat 60 s)",
      "🏆 Classement Cookies revient sur le total lifetime (le cycle hebdomadaire continue en interne pour les récompenses top 3)",
      "☕ Nouveau thème édition limitée « Cookie & Espresso » — gradient vertical crème → espresso, drop barista légendaire",
      "📲 Carte d'installation PWA directement dans l'onboarding (Android/Desktop) + instruction Safari pour iOS",
      "🧠 Pool de quiz enrichi : 65 questions au lieu de 33 (+22 culture café + 10 nouvelles Expert : pression espresso 9 bars, Geisha Panama, Yirgacheffe…)",
      "🎟️ De nouveaux codes promo à dénicher (cookies, café, action $CKM)",
      "🛡️ Fix anti-exploit : les packs actions $CKM en cookies deviennent achetables une seule fois (avant : achat répété possible)",
      "📛 Pseudo « Ethan Cuomo » dans les crédits, le splash et les mentions de l'auteur",
      "✨ Petit polish UI : nom long du leader plus jamais coupé dans le classement, titre lisible sur le nouveau thème",
    ],
  },
  {
    version: '1.12.0',
    date: '2026-05-10',
    title: "📈 Refonte du marché $CKM — anti-manipulation",
    changes: [
      "📊 Marché élargi : 10 000 actions disponibles (au lieu de 1 000)",
      "💎 Bonus de hold : +10 % après 1 h, +30 % après 24 h, +100 % après 7 jours sur la PnL positive — récompense les hodlers patients",
      "⏱️ Cooldown 60 s entre 2 achats / 2 ventes / achat puis vente — fini le pump-and-dump rapide",
      "🛒 Max 20 actions par transaction (force à étaler ses gros ordres)",
      "🛡️ Circuit breaker auto si variation > 15 % en 5 min (pause 1 h)",
      "🔄 Mean reversion vers 100 — le prix revient naturellement vers son centre",
      "📉 Cap 5 % du marché par utilisateur (500 actions max — plus de whales)",
      "🏆 Bannières podium top 1-3 redesignées en mocha-caramel chaud",
      "⚖️ Cap écart top 1 / top 2 : +25 % (compétition plus serrée)",
      "🤝 Compensation automatique pour les ex-investisseurs lésés par l'incident pump-and-dump",
    ],
  },
  {
    version: '1.11.0',
    date: '2026-05-10',
    title: "⚖️ Rééquilibrage économique — fair-play renforcé",
    changes: [
      "🛡️ Suppression des items qui donnaient un avantage compétitif (Coup de Grâce, packs cookies, packs gros volumes d'actions)",
      "⚡ Boost café réajusté : +30 % au lieu de ×2 (impact plus modéré sur la progression)",
      "💎 La boutique premium garde uniquement avatars / skins / thèmes / musiques / 1 action $CKM (cosmétiques + utilitaires fair)",
      "🎯 Doubler le prochain gain et Skip Quiz toujours dispo — utilitaires limités",
      "🎫 Jetons VIP roue & slot inchangés — juste +tours, pas d'avantage",
      "🏆 Le marché et le classement deviennent purement compétitifs, sans raccourci payant",
    ],
  },
  {
    version: '1.10.0',
    date: '2026-05-10',
    title: "🎨 Cosmétiques premium + raretés ☕",
    changes: [
      "🧑‍🚀 Avatar Cosmonaute Caféiné (25 ☕) + Skin Cookie Galactique (7 ☕)",
      "⏰ Bonus VIP cappés à 1 achat / jour — fini le cumul de boosts",
      "⚡ Popup festif quand un boost amplifie un gain mini-jeu",
      "💳 Bundle Stripe 0,99 € : 10 ☕ → 15 ☕ (meilleur ratio entry-level)",
      "🌑 Fix : nav du bas ne disparaît plus en thème Noir & Blanc",
      "🍪 Décor festif : cookies tournants en arrière-plan pour le thème Pâte de Cookie",
    ],
  },
  {
    version: '1.9.0',
    date: '2026-05-10',
    title: "☕ Monétisation, prestige & refonte café",
    changes: [
      "💳 Paiement Stripe pour acheter des cafés (15 / 50 / 200 ☕)",
      "🌟 Système Prestige (Renaissance) — niveau 16 'Ascendant Caféiné' à 20000 XP",
      "👑 Couronnes visibles dans le classement à chaque prestige (×10 % bonus permanent sur tous les gains 🍪)",
      "⚡ Nouveaux boosters consommables : ×2 cookies (1 h), Skip quiz, Doubler prochain gain",
      "🎫 Catégorie 'Bonus VIP' regroupe tous les jetons + boosters dans le Premium",
      "🎰 Cap 50 parties / jour sur la Machine à Sous + ticket 50 parties (3 ☕)",
      "🐺 Avatar Loup Mocha (remplace Dragon Espresso) — fourrure mocha sur fond espresso sombre",
      "🌑 Thème exclusif 'Noir & Blanc' (greyscale total) — code promo distribué par le créateur",
      "🍪 Thème 'Pâte de Cookie' — drop ultra-rare à dénicher en jeu",
      "🎓 Tutoriel élargi : 7 étapes couvrant classement, marché, boutique en plus",
      "💰 Économie café rééquilibrée : sources -45 %, stock global reset à 0",
      "🐛 Fix : sync cross-device cassait les paiements Stripe (race upsert client)",
    ],
  },
  {
    version: '1.8.0',
    date: '2026-05-09',
    title: "🛍️ Boutique enrichie + audio complet",
    changes: [
      "🎨 9 nouveaux skins cookie (Caramel, Onyx, Doré, Phoenix, Originel…)",
      "🏷️ 9 titres couleur shimmer pour ton pseudo (Mousse → Cosmique)",
      "🎵 5 nouvelles musiques (Café du Matin, Velvet Smoke, Beat de l'Empereur, Veillée Lofi, Nuit Cosmique)",
      "📈 Packs $CKM — achète directement 5 ou 10 actions",
      "🎟️ Item premium 'Révéler Code Promo Rare' (5 ☕ niv 13)",
      "🔊 8 sons d'effets dédiés (caisse, jackpot, slot, bulle…)",
      "💧 Bruit du café qui coule pendant le 'Stop le café'",
      "🪟 Sons sur tous les jeux silencieux (Click, Memory, Reflex, Devine)",
      "👤 Sélecteurs Skin & Titre dans le profil",
      "🛒 Chaque niveau a maintenant 3 ou 4 items à débloquer",
    ],
  },
  {
    version: '1.7.0',
    date: '2026-05-09',
    title: "🎰 Niveaux 11-15 + Machine à Sous",
    changes: [
      "🆙 5 nouveaux niveaux : Empereur Caféiné → Cookie Originel",
      "🎰 Nouveau mini-jeu Machine à Sous (débloqué niv 13)",
      "🛡️ 3 badges et 2 thèmes en plus dans la boutique",
      "🌌 Endgame XP→☕ décalé du niv 10 au niv 15 — plus de progression",
      "📜 Restauration complète de profil avec PIN sécurisé",
      "🔄 Récupère ton compte sur un autre appareil avec ton code + PIN",
    ],
  },
  {
    version: '1.6.0',
    date: '2026-05-08',
    title: "🎁 Cadeaux + niveaux 7-9 + anti-triche",
    changes: [
      "🎁 Offrir 50 🍪 ou 1 ☕ à un ami (max 3 cadeaux par jour)",
      "🏗️ Nouveau mini-jeu Pile de Tasses (niv 8) — empile sans tomber",
      "⬆️ Niveaux 7-9 remplis : Mocha Cosmique, Sage du Café, Maître Mythique",
      "💫 Bonus passif +15 % XP à partir du niveau 9",
      "🎓 Mode Expert Devine la commande (niv 7+, V60 / Geisha / Chemex…)",
      "🎰 Roue à 20 🍪 dès le niveau 8",
      "🛡️ Anti-triche Cookie Clicker v2 (cap 12 clics/s, détection pattern)",
      "🔇 Musique en pause quand l'app passe en arrière-plan",
      "🎨 Avatars : 8 onboarding + 9 premium thématisés café/cookie",
      "🐛 Fix : amitiés bloquées en pending par une RLS manquante",
    ],
  },
  {
    version: '1.5.0',
    date: '2026-05-07',
    title: "📈 Marché en ligne + réseau social",
    changes: [
      "📈 Marché $CKM 100 % online avec offre/demande partagée entre joueurs",
      "🏆 Classement marché par actions $CKM détenues",
      "⏰ Horaires marché : 6 h → minuit (heure locale)",
      "👥 Demandes d'amis bilatérales (envoyer / accepter / refuser)",
      "👤 Voir le profil d'un ami ou du top 1 du classement",
      "💬 Réactions emoji depuis le profil (👏 ☕ 🔥 🍪)",
      "📬 Inbox de notifications centralisée",
      "🏅 3 nouveaux badges secrets à découvrir",
      "🎉 Événements spéciaux : 3 défis avec thèmes limités + bonus ☕",
      "🐛 Fix : reset complet du profil + avatars cross-device",
    ],
  },
  {
    version: '1.4.0',
    date: '2026-05-06',
    title: "🎵 Audio complet",
    changes: [
      "🔊 Sons d'interface partout (tap, succès, modale…)",
      "🎵 4 musiques d'ambiance (Jazz Café, Bossa Nova, Café Parisien, Lounge Doré)",
      "☕ Pack premium ☕ : Lofi + Symphonie Royale",
      "🔇 Mute global + sélection de la piste en cours",
    ],
  },
  {
    version: '1.3.0',
    date: '2026-05-05',
    title: "☁️ Backend Supabase",
    changes: [
      "🌍 Profil synchronisé en ligne via Supabase",
      "🏆 Classement online avec vrais joueurs",
      "🎓 Tutoriel guidé pour les nouveaux",
      "✨ Splash screen lettre par lettre",
      "📱 PWA installable sur l'écran d'accueil",
    ],
  },
  {
    version: '1.0.0',
    date: '2026-05-02',
    title: "🎉 Lancement initial",
    changes: [
      "5 mini-jeux : Check-in, Devine la commande, Roue, Défi de clics, Stop café",
      "🛍️ Boutique : badges, titres, thèmes, avatars, skins, roues",
      "📊 Marché $CKM local",
      "👤 Profil avec progression sur 10 niveaux",
    ],
  },
];
